mv temp/6111.jpeg temp/6111.jpeg
mv temp/6115.jpeg temp/6115.jpeg
mv temp/arsenic.jpeg temp/arsenic.jpeg
mv temp/build-1.jpeg temp/build-1.jpeg
mv temp/build-2.jpeg temp/build-2.jpeg
mv temp/build-challenge.jpeg temp/build-challenge.jpeg
mv temp/cadlab.jpeg temp/cadlab.jpeg
mv temp/centrifugecal.jpeg temp/centrifugecal.jpeg
mv temp/gearboxfront.jpeg temp/gearboxfront.jpeg
mv temp/gearboxside.jpeg temp/gearboxside.jpeg
mv temp/lamp.jpeg temp/lamp.jpeg
mv temp/robot.jpeg temp/robot.jpeg
mv temp/robotback.jpeg temp/robotback.jpeg
mv temp/robotfront.jpeg temp/robotfront.jpeg
mv temp/robotside.jpeg temp/robotside.jpeg
mv temp/rtn.jpeg temp/rtn.jpeg
mv temp/si-description.jpeg temp/si-description.jpeg
mv temp/tech-pt-portal.jpeg temp/tech-pt-portal.jpeg
mv temp/yellow-team-kresge.jpeg temp/yellow-team-kresge.jpeg
mv temp/yellow-team-pic.jpeg temp/yellow-team-pic.jpeg
